[tool.black]
line-length = 100

[tool.isort]
line_length = 100
force_single_line = true
lexicographical = true
order_by_type = false
add_imports = ["from __future__ import annotations"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
precision = 2
fail_under = 100
show_missing = true
skip_covered = true
include = ["src/anki_formatter/formatters/*"]

[tool.pytest.ini_options]
pythonpath = "src"
